#ifndef OBJECTS_DETECTION_DEFINE_DATA_H
#define OBJECTS_DETECTION_DEFINE_DATA_H

#define RAW_MODEL_NUM 3
#define NUM_SCALES 15
#define CASCADE_STAGES_NUM 1064

#define CASCADE_THRESHOLD_OFFSET 0.0f
#define CASCADE_THRESHOLD_OFFSET_DECAY 1E-5f
#define CASCADE_THRESHOLD_ADDITIVE_OFFSET 0.0f

#define MAX_PEDESTRIAN_HEIGHT 240
#define MIN_PEDESTRIAN_HEIGHT 95

#define RAW_MAX_DETECTION_COUNT 1024
#define MAX_DETECTION_COUNT 64

#endif // OBJECTS_DETECTION_DEFINE_DATA_H

